### ISSUE TITLE
Solver.duplicateModel produce invalid copy when cumulative constraints are in a model

### ISSUE THREAD

**Issue by gregy4** [chocoteam/choco3#266]
Hello,

  it seems to me that there's a bug in a code that duplicates cumulative constraints - both version PropGraphCumulative and PropFullCumulative.

I tried to use more than one solver via following code ...

    MasterSolver ms = new MasterSolver();
    ms.populate(solver, 1);
    ms.findOptimalSolution(ResolutionPolicy.MINIMIZE, objectiveVar);

alternative with direct calling of Solver.duplicateModel gave me same result

    Solver solver = masterSolver.duplicateModel();
    solver.findOptimalSolution(ResolutionPolicy.MINIMIZE, objectiveVar);

when cumulative constraints were present, attached stacktrace was generated.

![stacktrace](https://cloud.githubusercontent.com/assets/5640112/6021455/3e898aec-abb6-11e4-9b8f-919655ea20ab.png)

My model is quite big, I'll try to make smaller subset to demonstrate a bug. The bug was reproduced in version 3.3.0 and current develop branch on various input data for my model.

**Comment by cprudhom** [comment]
Thank you for the bug report. I'll try to figure this out without your minimal working example, but if you can give me one, it will certainly be easier.

**Comment by gregy4** [comment]
Thanks for explanation, I tried to give a breakpoint to the comparator.
Task start has domain [1223,44294], task end has domain [750,1223] and a duration is fixed to 30, shouldn't assert failt also when eub[i]==slb[i] and eub[i]>slb[i] ?

To answer your question, I tried two variants - run only duplicated solver without running original solver and run them in parallel (via first example with MasterSolver)

**Comment by cprudhom** [comment]
There seems to be another error: how a task with such start, end and duration does not fail?

To be clearer: the duplication of a model can not be done before solving it (otherwise an error is thrown).
I have the feeling that the error comes from your model but is showed thanks duplication.
Could you try to give me a working example: I ensure anonymity of the model and the data, if you need it.
