### ISSUE TITLE
solver#findOptimalSolution()

### ISSUE THREAD

**Issue by fhermeni** [chocoteam/choco3#268]
It prevents me to store the intermediary solutions as it forces a LastSolutionRecorder.

In my case, I want to maintain the previously computed solutions to analyse the practical improvements (and not just tracking the objective value)

**Comment by cprudhom** [comment]
What about plugging a `AllSolutionRecorder` (extending `ISolutionRecorder`) ?
Or create your own `ISolutionRecorder`?

**Comment by fhermeni** [comment]
findOptimalSolution() plug its own then call solve(). So it is too late to provide your own solution recorder.
I switched to a workaround that store Solution objects created inside a IMonitorSolution.

**Comment by cprudhom** [comment]
You need to plug it before solving the problem, that will work since Solver will not erase the IMonitorSolution object.
```java
        AllSolutionsRecorder sols = new AllSolutionsRecorder(solver);
        solver.findOptimalSolution(ResolutionPolicy.MINIMIZE, obj);
        System.out.printf("nb sol: %d\n", sols.getSolutions().size());
```

**Comment by fhermeni** [comment]
It works.
I was in faulty situation as I used getSolutionRecorder() to access the AllSolutionsRecorder I registered. I didn't though about your approach.

THanks
