### ISSUE TITLE
Interfacing the Collections library

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco3#269]
It seems that trove is not the fastest library for collection anymore (http://java-performance.info/hashmap-overview-jdk-fastutil-goldman-sachs-hppc-koloboke-trove-january-2015/), but, refactoring such dependency should include defining interfaces to ease modification of such library dependency.
Using fastutil, for instance, which extends the Java Collections Framework, would certainly be a good choice (not to say that it seems to be a very good alternative to trove)

**Comment by fhermeni** [comment]
Hi

Be careful with being over-optimistic.
1/ Is the HPC collection library of Choco (trove currently) the bottleneck of Choco performance ?
1/ With maps < 1M keys, the gap btw. the implementations is not that important

What I mean is this migration might be costly (and boring) to do. So, if the expected benefit for you is a performance gain, think twice

Fabien

**Comment by JLiangWaterloo** [comment]
> refactoring such dependency should include defining interfaces to ease modification of such library dependency

You might end up losing performance by adding another layer of abstraction

**Comment by cprudhom** [comment]
This had more to do with a personal note about underlying collections. 
Both of you are right.
Before doing such a deep refactoring, it must be evaluated anyhow.
