### ISSUE TITLE
IntVar.removeInterval should not be used blindly

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco3#270]
In order to avoid misunderstanding and unexpected behavior while using explanations, the `IntVar.removeInterval(...)` method should not be used anymore.
Most of the time it is required to fix AC filtering on bounded variables, which is counter-productive (all supports are evaluated, even though only those on bounds need to be evaluated) and leads to incorrect explanations (or errors) when used with explanations.  

I suggest to set it as deprecated and patch propagators in consequence.

**Comment by cprudhom** [comment]
what if we add a new method to IntVar, such as `removeIntervals(ranges)` where `ranges` is an object which allow range iteration. The `ranges` could be created and maintained by the propagator who uses it (to avoid multiple creations).
A possible concret implementation of ranges could be a `BitSet`.

**Comment by cprudhom** [comment]
To have an idea of the performance decreases induced by replacing `removeInterval(int, int, cause)` by a sequence of `removeValue(int, cause)`, run the following test:
```java
@Test(groups = "1s")
    public void testRemInt() throws ContradictionException {
        Solver s = SolverFactory.makeSolver();
        int MAX = 9999999;
        IntVar v = VF.enumerated("D", 0, MAX, s);
        long t = -System.currentTimeMillis();
        for (int i = 0; i < 20; i++) {
            s.getEnvironment().worldPush();
            v.removeInterval(0, MAX-1, Cause.Null);
            s.getEnvironment().worldPop();
            long c = System.currentTimeMillis();
            System.out.printf("RI: %dms\n", t + c);
            t = -c;
        }
        t = -System.currentTimeMillis();
        for (int i = 0; i < 20; i++) {
            s.getEnvironment().worldPush();
            for (int k = 0; k < MAX; k++) {
                v.removeValue(k, Cause.Null);
            }
            s.getEnvironment().worldPop();
            long c = System.currentTimeMillis();
            System.out.printf("RV: %dms\n", t + c);
            t = -c;
        }
    }
```
The performance decrease comes from the loss of even promotion, as depicted by the test.
For instance, not removing the lower bound reverses the performances.

**Comment by cprudhom** [comment]
I will add the two following APIs for `IntVar`:
- `updateBounds(int, int, Cause)`: which updates both lower and upper bounds in one call,
- `removeAllValuesBut(IRemovals, Cause)` : which removes all values but the ones in `IRemovals`.

The former is just syntactic sugar, the latter, though, aims at reducing the number of calls to the environment and the propagation engine on variable's domain modificatio (the test shown in a previous comment exhibit such case).

**Comment by jgFages** [comment]
I find a bit strange to name IRemovals an object that contains values that are not removed...
I would go for something more generic such as IValues...

**Comment by cprudhom** [comment]
I already changed it in my branch ;)
