### ISSUE TITLE
Running with released Linux distributions

### ISSUE THREAD

**Issue by shevek** [chocoteam/choco3#274]
Hi,

I'm running Ubuntu Vivid, which is pretty cutting edge (it's still in beta) but the tools here are still not up-to-date enough to build and run Choco. My downstream customers are running Ubuntu Trusty or RHEL and Java 7.

Can you please publish on Maven Central built using java 7, and in class file format 51.0 instead of 52.0 so that it can be included in products?

Thank you.

S.

**Comment by shevek** [comment]
Addendum: I'm a long time user of choco 2, but that's not on Maven Central. I was willing to update all our software to 3 so we can avoid carrying our own binaries.

**Comment by cprudhom** [comment]
Hi Shevek,

Thank you for your feedback. 
We understand your request,and we certainly moved too fast to java 8 but it has been done some months ago and we don't feel like maintaining two versions of the same code for two different JVMs. 
Maybe an alternative would be to downgrade the source target to java 7... But it seems like a kind of regression to me.

CP

**Comment by alessandroleite** [comment]
Shevek,

I've downgrade the code to Java 7 and it did not demand me much time. So far, the Java 8 features on Choco's source-code are: (a) lambda expressions, (b) default methods, (c) stream, and (d) method references.

**Comment by shevek** [comment]
What is the chance of maintaining the default branch use Java 7? I don't really want to maintain a branch of choco on top of all our other work, but until java 8 has general acceptance (e.g. appears in default Linux distributions) we cannot make practical or industrial use of this code.

**Comment by shevek** [comment]
@cprudhom If @alessandroleite can put up a PR for the work, would you accept it?

**Comment by cprudhom** [comment]
Well, as I said, I don't want to spend time maintaining two versions of the code, and downgrading to java7 looks like a regression to me. If we found a way to easily maintain the two versions, I would certainly do it.

**Comment by cprudhom** [comment]
Maybe I could consider, for each release, branching the master branch, and modifying the code in order to be java7 compliant, and push it to MCR. Would it be an acceptable solution?

**Comment by shevek** [comment]
Any solution which lets us have a Maven Central dependency which runs in Java 7 is perfect. Thank you.

**Comment by alessandroleite** [comment]
The project should replace (a) lambda expressions by functions or similar approaches (e.g., Guava's functions -- https://code.google.com/p/guava-libraries/wiki/FunctionalExplained); and (b) default methods and other Java's 8 features by aspect (i.e., AspectJ).
