### ISSUE TITLE
Search strategy

### ISSUE THREAD

**Issue by mwahbi** [chocoteam/choco3#289]
Hi all, 

Is is possible to keep the default search strategies on all variables and only set a search strategy on a subset of variables. The problem I've had is as follows. Let say I have 3 variables x, y and z and 3 constraints c_xy, c_xz, and x_yz. If I define  a search strategy (ss1) by only on x and z and call solver.set(ss1); I will get solutions that omit constraints c_xy and x_yz. I think that this comes from how set(AbstractStrategy... strategies) is implemented. Is it possible to keep previous search strategies when calling set(AbstractStrategy... strategies)?

**Comment by jgFages** [comment]
Hi Mohamed,

Yes you can! 
Note that the setter may have multiple search strategies as argument
solver.set(s1,s2...);
And you can retrieve the current search strategy (potentially composite) with solver.getSearchLoop().getStrategy()
So, you should do something like:
solver.set(myNewStrategy,solver.getSearchLoop().getStrategy());

**Comment by mwahbi** [comment]
Thank you @jgFages 
Magnificent, I tried it and it works. But It only works if I called set beforehand in my configureSearch(). I guess because before this stage there is no default search strategy. 
Cheers,

**Comment by mwahbi** [comment]
I should also say that it only works if my myNewStrategies cover all variables!

**Comment by jgFages** [comment]
Yes the default search strategy is created just before solving in case no search is defined, so you need to create you own "complete" search.
And yes the overall strategy should cover all variables, but you can do it in two steps:
solver.set(mySearch(X), ISF.lexico_LB(ArrayUtils.append(X,Y,Z)));

**Comment by mwahbi** [comment]
Okay I see, thank you Jean-Guillaume.
