### ISSUE TITLE
Default search strategy

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco3#290]
We need to discuss what should be the default search strategy for any types of variable.
Now, for integer variables, it is ``lexico_LB``, which is not motivated.
Should it be a bb search strategy combined with LC, explanations, LNS, ...?
In addition, we should print the fact that the default strategies are used (Moreover, I suggest to split the current message in two: one before solving, and another after solving with different info printed out, if everyone agrees, I create a new issue).

**Comment by jgFages** [comment]
Yes, the user should know what the search is.

I suggest DomWDeg+LC. It is efficient while simple. It has no restart, no learning preprocessing, and it remains an exact approach. 

As far as I know, the relevance of using explanations really depends on the kind of constraints that are in the model, so I do not think it is a good default choice.

**Comment by cprudhom** [comment]
OK, I agree. 
One remark though, Dom/WDeg breaks ties randomly, may be we could consider a version wherein ties are broken lexicographically. 
What about the message?

**Comment by cprudhom** [comment]
Suggestion:
+ Integer/boolean: keep the creation order (dom/wdeg+lc)
+ set: enforce first
+ real: cyclic
+  objective: move if any in a complementary search (LB for min, UB for max).

**Comment by mwahbi** [comment]
Hi Charles, Jean-Gui, 
I would ask you why it is not the original DomOverWDeg (min{dom / wdeg }) that is implemented, were dom is the domain size and wdeg is the the weighted degree computed by weight(IntVar v)?. If it was like that the degrees could be used to break the ties.  
Cheers,

**Comment by cprudhom** [comment]
@mwahbi It is the original Dom/Wdeg, it is just at the beginning, when all weigths are equal to 1, there could be some ties, and they can be broken randomly or lexicographically.
Then, when the learning process goes on and the weights start to vary, there is (almost) no tie breaking anymore.

**Comment by mwahbi** [comment]
@cprudhom Maybe, my remark was not clear! 
In "Boosting Systematic Search by Weighting Constraints. ECAI 2004" page 3, (http://www.cril.univ-artois.fr/~lecoutre/research/publications/2004/ECAI2004.pdf) 
*wdeg* is equivalent to method (line 150) private int weight(IntVar v); 
https://github.com/chocoteam/choco3/blob/master/choco-solver/src/main/java/org/chocosolver/solver/search/strategy/selectors/variables/DomOverWDeg.java

However, in line  132,  long c2 = _d1 * degree * weight; 
So, my remark was that maybe line 132 should be: long c2 = _d1 / weight; Right?

**Comment by cprudhom** [comment]
In the article, they said : " (dom/wdeg is) an heuristic that selects first the variable with the smallest ratio current domain size to current weighted degree."
In our case, we want to avoid using the `/` operator.
Let consider 2 variables:
- v1: dom size = 100, weight = 2, degree = 10 and
- v2: dom size = 120, weight = 3, degree = 4.
 
Then
`dom(v1) / (weight(v1)*deg(v1) < dom(v2) / (weight(v2)*deg(v2)`
and 
`dom(v1) * (weight(v2)*deg(v2) < dom(v2)  (weight(v1)*deg(v1)`
will both return `true` (v1 has a smaller ration than v2) but without using division.

I admit, though, that names of temporary variables (`c1`,`c2`, `_d1` and `_d2`) are not well chosen.

**Comment by mwahbi** [comment]
Thank you Charles for your patience, 
Ouuuuups, I didn't pay attention to that tiny detail. Now, I understand your implementation. But, my remark steel holds for <code>deg(vi)</code>. 
If my understanding of the ECAI2004 paper is correct, there should not be <code>deg(vi)</code> at all in the measure of DomOverWDeg. <code>wdeg</code> does not mean <code>weight(vi)*deg(vi)</code> but it is simply <code>weight(vi)</code>. That is, line 132 should be: 
<code>long c2 = _d1 * weight;</code>
Right?

**Comment by cprudhom** [comment]
euh... you're bloody right, I missed that!
I think it can wait until monday, it's "la fête du travail" today, I'll go buy some lilies of the valley. Btw, thank you for the bug report.

**Comment by mwahbi** [comment]
I forget "la fête du travail", we are working today in Ireland, we don't have that. Next Monday is a bank holiday here. So enjoy your fête and the long-weekend (I miss lilies of the valley). 
Cheers
