### ISSUE TITLE
Add a user-friendly way to define multi-thread resolution

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco3#293]
It already exists, but it is not easy to define

**Comment by cprudhom** [comment]
The multi-core resolution needs to be managed within the `Solver` class, through a method which sets the number of cores to use.
When set to `n=1`, nothing should change from the current behavior of `Solver`.
When set to `n>1`, a distributed resolution should start.

I believe that the easiest way to do is to add a private array of `Solver` in `Solver` in order to deal with multi-core resolution. 
Methods remaining unchanged: `getSearchLoop()`, `getObjectiveManager()`, `getStrategy()`, `getEngine()`, `getVars()`, `getNbVars()`, `getVar()`, `retrieveIntVars()`, `retrieveBoolVars()`, `retrieveSetVars()`, `retrieveRealVars()`, `getCstrs()`, `getNbCstrs()`, `getName()`, `getEnvironment()`, `getMeasures()`, `getExplainer()`, `getSolutionRecorder()`, `getSettings()`, `getEventObserver()`, `set()`, `plugMonitor()`, `add()`, `makeCompleteSearch()`, `associates()`, unassociates()`, post()`, `postTemp()`, `unpost()`, `getMinisat()`, `getNogoodStore()`, `toString()`, `writeInFile()`, `writeInFile()`, `readFromFile()`, `duplicateModel()`, `getNbIdElt()`, `nextId()`, `getIbex()`, `propagate()`.

Only the following ones should be adapted when `n>1`:
`isFeasible()`, `setFeasible()`, `hasReachedLimit()`, `findSolution()`, `nextSolution()`, `findAllSolutions()`, `findOptimalSolution()`, `findAllOptimalSolutions()`, `findParetoFront()`, `findOptimalSolution()`, `solve()`, `isSatisfied()`

Their excepted behaviors are the following:
- on a call to `protected void solve()` (triggered by  `findSolution()`, , `findAllSolutions()`, `findOptimalSolution()`, `findAllOptimalSolutions()`, `findParetoFront()`, `findOptimalSolution()`), the slaves are reset and computed again,  
- on a call to `nextSolution()`, the slaves are kept as is. However, should we restore them to their previous state ? Or ...?
- `isFeasible()` and `isSatisfied()` consider one slave among all to answer,
-  `hasReachedLimit()` considers all slaves to answer.

What about the way solutions are recorded? and the search monitors? and the measures? 
Maybe we should consider a kind of store for variables and constraints, to ease duplication ? 

In consequence, the following class should be removed: `MasterSolver`, `SlaveSolver`, `AbstractParallelMaster` and `AbstractParallelSlave`.

**Comment by cprudhom** [comment]
The code I suggest is to add the method `setNumberOfThreads()` method in `Solver` in order to enable must-thread resolution.
The multi-thread resolution is managed by an external but user-hidden `SolverGuide` which is in charge of duplicating the original model, and driving the various resolutions.

Some questions remain though:
- search monitors are related to resolution process and thus do not have to be duplicated. Exception: limits, solution recorders, measures and statistics. 
- how to get solutions as long as we only deal with only one solver, the one declared by the user, 
- should we merge solutions in a set in order to avoid multiple occurrences of the same one
 
OR, should we change more deeply the code in order to natively support multi-thread resolution.
This induces separating model (variables and constraints) and solver (resolution), declaring an resolution interface `Solver` with the various resolution methods (some could be specific).
Doing so will impact all the code since variable and constraint refer to their `Solver`....

**Comment by cprudhom** [comment]
beta version [patch](https://gist.github.com/cprudhom/6eef674624fc9689dfd8/8264decc5ab7d07521c6c53d4cb571bb10596627)

**Comment by fhermeni** [comment]
Hi

My 1 cent;
I got this issue in BtrPlace.
I decided to split the model from the solving process: http://www.btrplace.org/apidocs/index.html?org/btrplace/scheduler/choco/runner/InstanceSolver.html <http://www.btrplace.org/apidocs/index.html?org/btrplace/scheduler/choco/runner/InstanceSolver.html>
I think it is quite clean, but indeed it requires refactoring.
By default, BtrPlace uses the SingleRunner but the user can choose the InstanceSolver to use using a single setter: http://www.btrplace.org/apidocs/index.html?org/btrplace/scheduler/choco/ChocoScheduler.html <http://www.btrplace.org/apidocs/index.html?org/btrplace/scheduler/choco/ChocoScheduler.html>


BR
Fabien

**Comment by cprudhom** [comment]
What I dislike in that propal is that I have the feeling to move back to choco2:
- the objects are duplicated: one model version, one solver version,
- the translation from model to solver comes at a cost,
- adding new variables/constraints lead to complex operations.

**Comment by fhermeni** [comment]
Indeed but that is for different reasons.
If you want to avoid duplication, then « just » makes the solver completely thread-safe. This might lead to sth. completely slow for the majority of the users and very hard to implement correctly.
Otherwise makes as much as you can stateless to avoid duplication.

**Comment by cprudhom** [comment]
but duplication is needed, since variables' domain cannot be shared.

**Comment by cprudhom** [comment]
Version 3.3.2 deals with multi-thread resolution in a very easiest way:

```java
int n =4; // number of solvers to use                                                          
List<Solver> solvers = new ArrayList<>();                                                      
for(int i = 0 ; i < n; i++){                                                                   
    Solver solver = new Solver();                                                              
    solvers.add(solver);                                                                       
    readModel(solver); // a dedicated method that declares variables and constraints           
    // the search should also be declared here                                                 
}                                                                                              
SMF.prepareForParallelResolution(solvers);                                                     
solvers.parallelStream().forEach(Solver::findSolution);                                        
// or solvers.parallelStream().forEach(s -> s.findOptimalSolution(ResolutionPolicy.MAXIMIZE)); 
}                                                                                              
```

**Comment by brunoolivieri** [comment]
Hi cprudhom!

Please, how to get results back? Is not clear after all..

Bests!
