### ISSUE TITLE
fast way to get first unitialized variable in a strategy

### ISSUE THREAD

**Issue by gregy4** [chocoteam/choco3#299]
Hello,
  so far I used simple for loop to get first uninitialized variable in a branching strategy.

    Variable decisionVariable;
    for (Variable var : vars) {
         if (var.isInstantiated()) {
              decisionVariable = var;
              break;
         }
    }

  Profiler showed me that the loop can be time consuming with thousands of variables.
  In case variables are instantiated in order defined by order in an array it is possible to use currentDepth of searchloop to skip for sure instantiated variables.

   for (int iVar=solver.getSearchLoop().getCurrentDepth(); iVar < vars.length; ++iVar){
            if (!vars[iVar].isInstantiated()) {
                decisionVariable = vars[iVar]);
                break;
            }
   }

  Another speedup can be to not compute current depth of searchloop in a loop on every call and store depth in decision instance - good candidate can be Decision.setPrevious method.

  If there's no faster way to get first uninitialized variable in a strategy or an array, is it possible to optimize SearchLoop.getCurrentDepth method ?

**Comment by jgFages** [comment]
Hi Jan-G,

Using the current depth does not look like a good solution to me.
I suggest you to use a backtrackable integer to store the index of the last unfixed variable.
Do you know how to do that?

Best,

Jean-G

**Comment by gregy4** [comment]
Hi Jean,
  I looked at the sources and it seems that backtrackable integer works for me even better.
  I created in init method a variable
       idxUnfixedVar = solver.getEnvironment().makeInt(0);

    and modified the loop
for (int iVar=idxUnfixedVar.get(); iVar < vars.length; ++iVar) {
     if (var.isInstantiated()) {
          decisionVariable = var;
          idxUnfixedVar.set(iVar);
          break;
     }
}

Is my code correct ?

**Comment by jgFages** [comment]
Shouldn't the "if" statement be the opposite (i.e. If not instantiated)?

**Comment by gregy4** [comment]
Yes, you are right. Exclamation mark is missing, fortunatelly I missed it only in the text and not in the real code :-)

**Comment by jgFages** [comment]
Good! So the code looks fine!
