### ISSUE TITLE
inconsistency between show and print

### ISSUE THREAD

**Issue by jgFages** [chocoteam/choco3#303]
There is an inconsistency between printStat and showStat.

showStat gives:

```
- Solver features:
	Variables : 55
	Constraints : 18
	Default search strategy : no
	Completed search strategy : no
- Incomplete search - Unexpected interruption.
	Solutions: 0
	Building time : 0,125s
	Initialisation : 0,013s
	Initial propagation : 0,016s
	Resolution : 0,016s
	Nodes: 0 (0,0 n/s) 
	Backtracks: 0
	Fails: 1
	Restarts: 0
	Max depth: 0
	Memory: 0mb
	Variables: 55
	Constraints: 18
```

whereas printStat gives:

```
- Complete search - No solution.
	Solutions: 0
	Building time : 0,125s
	Initialisation : 0,013s
	Initial propagation : 0,016s
	Resolution : 0,022s
	Nodes: 0 (0,0 n/s) 
	Backtracks: 0
	Fails: 1
	Restarts: 0
	Max depth: 0
	Memory: 0mb
	Variables: 55
	Constraints: 18
```

1) Le showStat should say "search complete - no solution"
2) For homogeneity, the print should also include the solver features

**Comment by cprudhom** [comment]
1) Well, it is strange, since `showStatistics(solver)` calls `printStatistics(solver)` on `searchLopp.close()`. How did you generate the trace?

2) ok

**Comment by jgFages** [comment]
I took the first sample I found. Actually, I think it comes from the fact that it is called between before and after close. Perhaps something is updated right after it...

**Comment by cprudhom** [comment]
OK, I got it, thanks.
