### ISSUE TITLE
Complete search - no solution but isSatisfied() == UNDEFINED

### ISSUE THREAD

**Issue by fhermeni** [chocoteam/choco3#309]
I cannot send to you the model but it contains a MultiCostRegular constraint (seems buggy at some point but we will go on that later)
The solver proved there is no solution but the constraints still reply with ESat.UNDEFINED.

```
- Complete search - No solution.
	Solutions: 0
	Building time : 0,317s
	Initialisation : 0,000s
	Initial propagation : 0,034s
	Resolution : 0,035s
	Nodes: 0 (0,0 n/s) 
	Backtracks: 0
	Fails: 1
	Restarts: 0
	Max depth: 0
	Memory: -1mb
	Variables: 24
	Constraints: 18
Esat = UNDEFINED
```
Any idea about the possible situation ?

**Comment by cprudhom** [comment]
Did you call `solver.isFeasible()` or `solver.isSatisfied()` ?

I assume you called `solver.isSatisfied()`. It may happen when not all variables are instantiated but the resolution fails at root node. Actually, almost all codes of `Propagator.isEntailed()` are like:
``` java
@Override
    public ESat isEntailed() {
        if (isCompletelyInstantiated()) {
            return ESat.eval(isSatisfied());
        } else {
            return ESat.UNDEFINED;
        }
    }
```

**Comment by fhermeni** [comment]
I called isSatisfied() indeed and some of the variables are not instantiated.
So my approach is the not the correct one or it is a corner case in the solver ?

**Comment by cprudhom** [comment]
Calling `solver.isSatisfied()` when `solver.isFeasible()` returns `ESat.FALSE` seems strange to me indeed.

**Comment by cprudhom** [comment]
To be clearer:
- `solver.isFeasible()` indicates whether the model has at least a solution (`ESat.TRUE`), the proof is made that the problem has no solution (`ESat.FALSE`) or no solution has been found but the entire search space has not been explored yet (`ESat.UNDEFINED`)
- `solver.isSatisfied()` checks the validity of solver current state, and as we all saw, the complete instantiation is kind of requirement.

So, maybe we can modify the code of `solver.isSatisfied()` to call `solver.isFeasible()` first and if it returns something different from `ESat.FALSE` the satisfaction can keep on.

**Comment by jgFages** [comment]
I vote for this
