### ISSUE TITLE
No solution but still incorrect initialisation

### ISSUE THREAD

**Issue by fhermeni** [chocoteam/choco3#310]
I have a model with a MultiCostRegular.
The constraint emits a Contradiction during the initial propagation.
This is catched that way in SearchLoop.java:
```
private void initialPropagation() {
   this.env.worldPush(); // store state before initial propagation; w = 0 -> 1
   try {
       solver.getEngine().propagate();
   } catch (ContradictionException e) {
       solver.getEngine().flush();
       solver.setFeasible(FALSE);
       interrupt(MSG_INIT);  
       smList.onContradiction(e);
       this.env.worldPop();
       return;
   }
```
interrupt() sets nextState to RESUME then the call to launch() lead to this exception:
```
            throw new SolverException("!! The search has not been initialized.\n" +
                    "!! Be sure you are respecting one of these call configurations :\n " +
                    "\tfindSolution ( nextSolution )* | findAllSolutions | findOptimalSolution\n");
```
So the problem here is that, to me, the solver is exaggerating the situation. Everything has been initialized correctly. The only real problem is that the solver detected the model has no solution during the initial propagation.

**Comment by cprudhom** [comment]
I refactored the `SearchLoop` object, this behavior is not encountered anymore.

**Comment by fhermeni** [comment]
I tried with the snapshot version. Now I have still a SolverException: "ERROR [Solver] The entire search space has been explored. Consider resetting the search loop."

**Comment by chocotrust** [comment]
Sorry, I didn't deploy the snapshot. That's done now.

**Comment by fhermeni** [comment]
Still got the issue with choco-solver-3.3.2-20150615.090524-4.jar (the last on the sonatype snapshot repository)

**Comment by fhermeni** [comment]
It is ok now. I messed up at something into my code.
Thanks for the patch
