### ISSUE TITLE
Iterating over a trivial solver

### ISSUE THREAD

**Issue by JLiangWaterloo** [chocoteam/choco3#313]
I've always iterated the solutions using the following idiom:
```java
Solver s = ...;
if (s.findSolution()) {
    do {
        // Do something
    } while (s.nextSolution());
}
```

However, with the latest develop branch the following code will throw an exception:
```java
Solver s = new Solver();
s.post(ICF.arithm(s.ONE(), "!=", s.ZERO()));
if (s.findSolution()) {
    do {
    } while (s.nextSolution());
}
```

The "s.nextSolution()" will throw an exception because "The entire search space has been explored." While this is certainly true, it is rather annoying because it prevents the above idiom from working in these special cases.

**Comment by chocotrust** [comment]
You're right, I totally missed that while refactoring `SearchLoop`.
Apparently, I had no test on taht
