### ISSUE TITLE
Unnecessary assert in sum(BoolVar[]...)

### ISSUE THREAD

**Issue by fhermeni** [chocoteam/choco3#314]
Hi

The constraint `sum(BoolVar[] VARS, IntVar SUM)` expects a non-empty array. It is controlled by an assertion.

When I generate a CSP, it means I then have to check the array length and implement the workaround. In practice, the assertion seems not required to me as the SUM variable will be equals to 0.

Regards,
Fabien

**Comment by cprudhom** [comment]
you're bloody right!
