### ISSUE TITLE
Sum of weighed variables

### ISSUE THREAD

**Issue by russellhoff** [chocoteam/choco3#319]
Is it possible to add a constraint of the sum of weighed variables? I can't find the way to make it.

**Comment by cprudhom** [comment]
Sure, it is called `scalar` in the integer constraint factory.

**Comment by russellhoff** [comment]
I'm trying to solve a CSP problem... And don't know how to represent the constraints I wanna introduce (perhaps somebody can lend me a hand).

I've got a number of people which I wanna bring them using some vehicles of determined capacity. So, what I want to know is how many vehicles do I need of each type to service people.

I've written a constraint: groupSize <= sum for each vehicle(vehicleSeatCapacity x variableQuantityOfVehicle)

Giving this example:

· Group Size: 9 People
· Vehicle types: 
    - Vehicle type 1: vehicles of 2 seats.
    - Vehicle type 2: vehicles of 7 seats.

The constraint would be: 9 <= (2.x) + (7.y)

What I've got difficulty is in translating it to Choco Solver code. For the time being, what I have is the following (considering your help of the scalar):


import java.util.ArrayList;
import java.util.List;

import org.chocosolver.solver.Solver;
import org.chocosolver.solver.constraints.IntConstraintFactory;
import org.chocosolver.solver.search.strategy.IntStrategyFactory;
import org.chocosolver.solver.trace.Chatterbox;
import org.chocosolver.solver.variables.IntVar;
import org.chocosolver.solver.variables.VariableFactory;

public class Main {

	private static Integer MAX_DOMAIN_VARS = 50;
	
	private static Grupo grupo = new Grupo(9);
	private static List<Vehiculo> vehiculos = new ArrayList<Vehiculo>();
	private static IntVar var1;
	private static IntVar var2;
	
	public static void main(String[] args) {

        // Creamos los vehículos:
		Vehiculo v1 = new Vehiculo(2, (float) 50);
		Vehiculo v2 = new Vehiculo(7, (float) 71);
		
		vehiculos.add(v1);
		vehiculos.add(v2);
		
		// Empezamos creando el solver:
		Solver solver = new Solver("csp");

		var1 = VariableFactory.bounded("var1", 0, MAX_DOMAIN_VARS, solver);
		var2 = VariableFactory.bounded("var2", 0, MAX_DOMAIN_VARS, solver);
		IntVar[] variables = {var1, var2};
		
		int[] costesVariables = {Math.round(v1.getCoste()), Math.round(v2.getCoste())};
				
		IntVar pers = VariableFactory.fixed(grupo.getPersonas(), solver);
		solver.post(IntConstraintFactory.scalar(variables, costesVariables, ">=", pers));
		
		// Estrategia de búsqueda:
		solver.set(IntStrategyFactory.lexico_LB(new IntVar[]{var1, var2}));
		
		// Buscar solución:
		solver.findSolution();
		
		// Imprimir las estadísticas de búsqueda:
		Chatterbox.printStatistics(solver);
		
		Chatterbox.printSolutions(solver);
		
	}

}

But I'm not sure if I'm doing it well... 

Besides, I would like to add another constraint, which would involve not the seats of the vehicles but the cost of each vehicle type:

min(sum for each vehicle(vehicleCost x variableQuantityOfVehicle))

This would involve picking the solution which would be cheaper.

In my example, we could add the vehicles' costs and enhance it:

· Group Size: 9 People
· Vehicle types: 
    - Vehicle type 1: vehicles of 2 seats and 15 of cost.
    - Vehicle type 2: vehicles of 7 seats and 18 of cost.

Therefore, the new constraint in this example would be: 

min(15.x + 18.y)

Thank you for your help!

**Comment by cprudhom** [comment]
Hi,

That seems to be an alternative of a [knapsack problem](https://en.wikipedia.org/wiki/Knapsack_problem) to me.
Have a look at the following constraint: `ICF.knapsack(...)`, that should fits your needs.
[Here](https://github.com/chocoteam/choco3/blob/master/choco-samples/src/main/java/org/chocosolver/samples/integer/Knapsack.java) is a sample made in choco using that constraint.

Most of the time, a first (sometime naive) model can be obtained by simply translating your mathematical model into a CP model. 
 
Hope it helps,
CP

**Comment by russellhoff** [comment]
IntConstraintFactory.knapsack(...) ensures that : 
- OCCURRENCES[i] * WEIGHT[i] ≤ TOTAL_WEIGHT 
- OCCURRENCES[i] * ENERGY[i] = TOTAL_ENERGY 
and maximizing the value of TOTAL_ENERGY. 

For my problem I need to modify it to ensure that:
- OCCURRENCES[i] * SEATS[i] ≥ TOTAL_PEOPLE
- OCCURRENCES[i] * COST[i] = TOTAL_COST
and MINIMIZING the value of TOTAL_COST

Do I need to modify the implementation of knapsack() method within IntConstraintFactory?

**Comment by russellhoff** [comment]
This is what I've done: https://github.com/russellhoff/choco-solver-inverted-knapsack

Look at my log (using the data of KnapsackInvertido):
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
** Choco 3.3.1 (2015-05) : Constraint Programming Solver, Copyleft (c) 2010-2015
- Solver features:
	Variables : 6
	Constraints : 1
	Default search strategy : no
	Completed search strategy : no
- Solution #1 found. 1 Solutions, Minimize coste = 121, Resolution 0,018s, 1 Nodes (54,2 n/s), 0 Backtracks, 0 Fails, 0 Restarts 
	coste = 121 var1 = 1 var2 = 1 .
- Incomplete search - Unexpected interruption.
	Solutions: 1
	Minimize coste = 121,
	Building time : 0,082s
	Initialisation : 0,017s
	Initial propagation : 0,018s
	Resolution : 0,021s
	Nodes: 1 (48,3 n/s) 
	Backtracks: 0
	Fails: 0
	Restarts: 1
	Max depth: 0
	Memory: 3mb
	Variables: 6
	Constraints: 1

The result seem correct, even if I change the group amount or the vehicles'. 

What to obtain more than one solution?  Changing here:

	@Override
	public void solve() {
		solver.findOptimalSolution(ResolutionPolicy.MINIMIZE, varCoste);
	}

by 

	@Override
	public void solve() {
		solver.findAllOptimalSolutions(ResolutionPolicy.MINIMIZE, varCoste, TRUE or FALSE);
	}

results in a long lasting loop (placing either true or false).

**Comment by cprudhom** [comment]
You should set the boolean to `true` (see why [here]{http://choco-solver.org/user_guide/3_solving.html#finding-all-optimal-solutions)).

What is a long loop ? 1sec? 10 sec? infinite?

**Comment by russellhoff** [comment]
Log file:
...
- Solution #384501 found. 384501 Solutions, Resolution 150,820s, 384501 Nodes (2.549,4 n/s), 0 Backtracks, 0 Fails, 384500 Restarts 
	coste = 121 var1 = 1 var2 = 1 .
- Solution #384502 found. 384502 Solutions, Resolution 151,943s, 384502 Nodes (2.530,6 n/s), 0 Backtracks, 0 Fails, 384501 Restarts 
	coste = 121 var1 = 1 var2 = 1 .
- Solution #384503 found. 384503 Solutions, Resolution 153,198s, 384503 Nodes (2.509,8 n/s), 0 Backtracks, 0 Fails, 384502 Restarts 
	coste = 121 var1 = 1 var2 = 1 .
- Solution #384504 found. 384504 Solutions, Resolution 154,324s, 384504 Nodes (2.491,5 n/s), 0 Backtracks, 0 Fails, 384503 Restarts 
	coste = 121 var1 = 1 var2 = 1 .
- Solution #384505 found. 384505 Solutions, Resolution 155,444s, 384505 Nodes (2.473,6 n/s), 0 Backtracks, 0 Fails, 384504 Restarts 
	coste = 121 var1 = 1 var2 = 1 .
- Solution #384506 found. 384506 Solutions, Resolution 156,558s, 384506 Nodes (2.456,0 n/s), 0 Backtracks, 0 Fails, 384505 Restarts 
	coste = 121 var1 = 1 var2 = 1 .
- Solution #384507 found. 384507 Solutions, Resolution 158,238s, 384507 Nodes (2.429,9 n/s), 0 Backtracks, 0 Fails, 384506 Restarts 
	coste = 121 var1 = 1 var2 = 1 .
- Solution #384508 found. 384508 Solutions, Resolution 159,935s, 384508 Nodes (2.404,1 n/s), 0 Backtracks, 0 Fails, 384507 Restarts 
	coste = 121 var1 = 1 var2 = 1 .
- Solution #384509 found. 384509 Solutions, Resolution 161,641s, 384509 Nodes (2.378,8 n/s), 0 Backtracks, 0 Fails, 384508 Restarts 
	coste = 121 var1 = 1 var2 = 1 .
- Solution #384510 found. 384510 Solutions, Resolution 163,887s, 384510 Nodes (2.346,2 n/s), 0 Backtracks, 0 Fails, 384509 Restarts 
	coste = 121 var1 = 1 var2 = 1 .
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at sun.text.resources.FormatData.getContents(Unknown Source)
	at sun.util.resources.ParallelListResourceBundle.loadLookupTablesIfNecessary(Unknown Source)
	at sun.util.resources.ParallelListResourceBundle.handleKeySet(Unknown Source)
	at sun.util.resources.ParallelListResourceBundle.keySet(Unknown Source)
	at sun.util.resources.ParallelListResourceBundle.containsKey(Unknown Source)
	at sun.util.resources.ParallelListResourceBundle$KeySet.contains(Unknown Source)
	at sun.util.resources.ParallelListResourceBundle.containsKey(Unknown Source)
	at sun.util.resources.ParallelListResourceBundle$KeySet.contains(Unknown Source)
	at sun.util.resources.ParallelListResourceBundle.containsKey(Unknown Source)
Exception in thread "Thread-0" java.lang.OutOfMemoryError: Java heap space
	at sun.text.resources.FormatData.getContents(Unknown Source)
	at sun.util.resources.ParallelListResourceBundle.loadLookupTablesIfNecessary(Unknown Source)
	at sun.util.resources.ParallelListResourceBundle.handleKeySet(Unknown Source)
	at sun.util.resources.ParallelListResourceBundle.keySet(Unknown Source)
	at sun.util.resources.ParallelListResourceBundle.containsKey(Unknown Source)
	at sun.util.resources.ParallelListResourceBundle$KeySet.contains(Unknown Source)
	at sun.util.resources.ParallelListResourceBundle.containsKey(Unknown Source)
	at sun.util.resources.ParallelListResourceBundle$KeySet.contains(Unknown Source)
	at sun.util.resources.ParallelListResourceBundle.containsKey(Unknown Source)
	at sun.util.locale.provider.LocaleResources.getDecimalFormatSymbolsData(Unknown Source)
	at java.text.DecimalFormatSymbols.initialize(Unknown Source)
	at java.text.DecimalFormatSymbols.<init>(Unknown Source)
	at sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.getInstance(Unknown Source)
	at java.text.DecimalFormatSymbols.getInstance(Unknown Source)
	at java.util.Formatter.getZero(Unknown Source)
	at java.util.Formatter.<init>(Unknown Source)
	at java.util.Formatter.<init>(Unknown Source)
	at java.lang.String.format(Unknown Source)
	at org.chocosolver.solver.search.measure.MeasuresRecorder.toString(MeasuresRecorder.java:429)
	at org.chocosolver.samples.AbstractProblem$1.run(AbstractProblem.java:142)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"

**Comment by cprudhom** [comment]
Did you defined any search strategy?
Did you set a restart strategy? Because it finds the same solution again and again

**Comment by russellhoff** [comment]
@Override
	public void configureSearch() {
		@SuppressWarnings("rawtypes")
		AbstractStrategy strat = IntStrategyFactory.lexico_LB(new IntVar[]{varCantidadVehiculos1, varCantidadVehiculos2});
        solver.set(new ObjectiveStrategy(varCoste, OptimizationPolicy.BOTTOM_UP), strat);
        //Chatterbox.showDecisions(solver);
	}

**Comment by cprudhom** [comment]
You only have 2 variables in your problem? I'm not sure you declare the right set of decisions variables (or you except the knapsack constraint to do more than it actually does).

**Comment by russellhoff** [comment]
Now I've only two variables (two vehicle types, two variables). Currently I'm testing it with One group of people and two vehicles, but I'll have several vehicles in a near future.

**Comment by cprudhom** [comment]
But, where did the restarts come from?

**Comment by russellhoff** [comment]
I don't know :S

**Comment by cprudhom** [comment]
Try with the default search strategy.
Is your repo up to date so I can have a look?

**Comment by russellhoff** [comment]
yes it's up to date :)

**Comment by cprudhom** [comment]
OK, got it. It comes from :
```java
solver.set(new ObjectiveStrategy(varCoste, OptimizationPolicy.BOTTOM_UP), strat);
```
You don't need to do that, except if you want a dichotomic search (that you didn't declare).
Delete that instructions and that should work like a charm.

**Comment by russellhoff** [comment]
thank you! I'm off work, so tomorrow I'll be checking it out.

**Comment by russellhoff** [comment]
@cprudhom I've updated my repo. It works!!!! 

Just note something. I've realised that no matter if I look for a single solution or "allSolutions",  I can only access to a single value of each variable.

**Comment by cprudhom** [comment]
You mean, once the resolution ends? 
That's normal: on a call to `findSolution()` the search stops on the first solution, if any, then variables are instantiated (domains reduced to singleton); on a call to `findAllSolutions(...)` or `findOptimalSolution(...)`, the last/best solution is restored when the search ends.

**Comment by russellhoff** [comment]
I've found it here http://choco-solver.org/user_guide/3_solving.html#enumerating-solutions. Thanks for all your help @cprudhom !
