### ISSUE TITLE
toString() of PropCondAllDiffInst gives incorrect result for n = 4

### ISSUE THREAD

**Issue by mrzb6** [chocoteam/choco3#322]
As demonstrated by this code example:
```java
Solver solver = new Solver();
IntVar[] vars = VF.boundedArray("var", 4, 0, 1, solver);
Constraint c = ICF.alldifferent_except_0(vars);
System.out.println(c.toString());
```
This results in the String
`AllDifferent_except_0 ([PropCondAllDiffInst(var[0], var[1], var[2], var[3], var[3])_except_0])`
which had me question myself when I first saw it.

Suggested fix for class `PropCondAllDiffInst`:
```java
private static final int NUMBER_OF_VARS_PRINTED = 4;

...

@Override
public String toString() {
	StringBuilder st = new StringBuilder();
	st.append(Arrays.stream(vars)
			.limit(Math.min(NUMBER_OF_VARS_PRINTED, n) - 1)
			.map(var -> var.getName())
			.collect(Collectors.joining(", ", "PropCondAllDiffInst(", "")));
	if (vars.length > NUMBER_OF_VARS_PRINTED) {
		st.append(", ...");
	}
	if(vars.length > 1) {
		st.append(", ");
	}		
	st.append(vars[n - 1].getName());
	st.append(")");
	st.append(condition);
	return st.toString();
}
```
Result for `n = 4` with the suggested fix:
`AllDifferent_except_0 ([PropCondAllDiffInst(var[0], var[1], var[2], var[3])_except_0])`
And for `n = 5`:
`AllDifferent_except_0 ([PropCondAllDiffInst(var[0], var[1], var[2], ..., var[4])_except_0])`

**Comment by cprudhom** [comment]
Thank you. 
It is already fixed in the develop branch (but may be not pushed yet).

Thank you for the bug report,
CP
