### ISSUE TITLE
NogoodFromSolutions trouble

### ISSUE THREAD

**Issue by mwahbi** [chocoteam/choco3#327]
@cprudhom Salut Charles,

I have a problem with the NogoodFromSolutions (see the example bellow). I am running a 8-queen problem with a nogood from solution on the first queen. I am expecting to have 8 solutions with no duplication on this variables (8 solution max). However I get 89 solutions. Could you check if there is mistakes/misunderstanding in my code or there is a problem in NogoodFromSolutions. 

Cheers, 
Mohamed

import org.chocosolver.solver.search.loop.monitors.NogoodFromSolutions;
import org.chocosolver.solver.search.strategy.IntStrategyFactory;
import org.chocosolver.solver.variables.IntVar;

public class NgdFromSolTest extends NQueenGlobal {

	@Override
	public void solve() {
		solver.findAllSolutions();
	}

	@Override
	public void configureSearch() {
		solver.set(IntStrategyFactory.minDom_LB(vars));
		solver.plugMonitor(new NogoodFromSolutions(new IntVar[] { vars[0] /* , vars[1] */}));
	}

	public static void main(String[] args) {
		args = new String[] { "-q=8", "-log=" + Level.SOLUTION };
		new NgdFromSolTest().execute(args);
	}
}

**Comment by cprudhom** [comment]
@mwahbi Salut, ca va?

You are right, there is a bug when dealing with nogood made of only one literal.
There is also a bug on backtracking, the nogoodstore is not called to check for newly added clauses.
So this needs to be fixed

**Comment by mwahbi** [comment]
@cprudhom je vais bien merci, j'espere que tout va a la merveille chez toi! 

I also tried some examples with more than one literal in the nogood and I found the same problem. 
Cheers, 
Mohamed
