### ISSUE TITLE
Chatterbox and custom streams

### ISSUE THREAD

**Issue by fhermeni** [chocoteam/choco3#331]
Hi
Chatterbox is cool for an easy reporting. However, it seems to me there is no way to print anything one something else than System.out.
So it would be great to enhance Chatterbox be able to provide the PrintStream I want to use.

Removing the static type and providing the PrintStream at instantiation would be enough (with a default constructor relying on System.out)

**Comment by cprudhom** [comment]
Sure, I was thinking about that too.
