### ISSUE TITLE
knapsack constraint is too strict

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco3#342]
The knapsack constraint is too strict.
See code in `IntConstraintFactory`:
```java
 return new Constraint("Knapsack", ArrayUtils.append(
                scalar(OCCURRENCES, WEIGHT, "=",TOTAL_WEIGHT).propagators,
                scalar(OCCURRENCES, ENERGY, "=", TOTAL_ENERGY).propagators,
                new Propagator[]{new PropKnapsack(OCCURRENCES, TOTAL_WEIGHT, TOTAL_ENERGY, WEIGHT, ENERGY)}
        ));
```
The sum of weights does not have to be equal to `TOTAL_WEIGHT` but smaller or equal to, as specified in the javadoc:
```html
    /**
     * Ensures that :
     * <br/>- OCCURRENCES[i] * WEIGHT[i] &#8804; TOTAL_WEIGHT
     * <br/>- OCCURRENCES[i] * ENERGY[i] = TOTAL_ENERGY
     * <br/>and maximizing the value of TOTAL_ENERGY.
     * <p>
     * <p>
     * A knapsack constraint
     * <a href="http://en.wikipedia.org/wiki/Knapsack_problem">wikipedia</a>:<br/>
     * "Given a set of items, each with a weight and an energy value,
     * determine the count of each item to include in a collection so that
     * the total weight is less than or equal to a given limit and the total value is as large as possible.
     * It derives its name from the problem faced by someone who is constrained by a fixed-size knapsack
     * and must fill it with the most useful items."
     *
     * @param OCCURRENCES  number of occurrences of an item
     * @param TOTAL_WEIGHT capacity of the knapsack
     * @param TOTAL_ENERGY variable to maximize
     * @param WEIGHT       weight of each item
     * @param ENERGY       energy of each item
     */
```
but the code is:

**Comment by jgFages** [comment]
If so, shouldn't the energy be >=, by symmetry?

**Comment by cprudhom** [comment]
I don't think so, since `TOTAL_ENERGY` is the variable to maximize, I believe that it has to be strictly linked to the occurrence variable.

**Comment by jgFages** [comment]
I am not very comfortable with this... What if you want to ensure a given power and minimize the weight?
It would be a very natural usage. 

I really like having two equalities. If the user really wants <= weight, he can create one extra variable and it would be ok. If you believe this would be slow, then the right approach would be to provide operators, but this requires more work :-)

**Comment by cprudhom** [comment]
I don't care about performances now scalar has been revamped ;)
But, if we strictly follow the definition given in the documentation, the constraint is not correct.
I agree with you that two equalities would provide more flexibility in the usage, but it has to be clearly said in the documentation.
So, either we correct the constraint or we correct the documentation.

**Comment by jgFages** [comment]
Of course code and documentation should fit 
I vote for updating the documentation !
