### ISSUE TITLE
Activity search strategy creates an infinite search loop

### ISSUE THREAD

**Issue by JLiangWaterloo** [chocoteam/choco3#344]
For example:

```java
public static void main(String[] args) {
    Solver s = new Solver();
    BoolVar a = VF.bool("a", s);

    s.set(ISF.activity(new IntVar[]{a}, 0));
    if (s.findSolution()) {
        do {
            System.out.println(a);
        } while (s.nextSolution());
    }
}
```

This program never terminates.

**Comment by cprudhom** [comment]
That comes from the combination of the followings:
1. activity-based search (ABS) restarts after each solutions,
2. after a restart, possibly the same search space (and thus solution) can be discovered again and again (note that, when dealing with constraint optimisation problem -- COP--, the problem does not happen),
3. in the small satisfaction problem you posted, all instantiations is solution.  

When dealing with constraint satisfaction problem --CSP--, you have to post a limit on the resolution to terminates it.

**Comment by jgFages** [comment]
Can't you use nogoodFromSolutions?

**Comment by JLiangWaterloo** [comment]
My apologies, I did not realize it did that.
