### ISSUE TITLE
[Choco 3.3.2] Bug in util.objects.IntMap.clear when using DomOverWDeg.getDecision 

### ISSUE THREAD

**Issue by RobertHilbrich** [chocoteam/choco3#348]
I stumbled upon a bug in IntMap. Here is the stacktrace:
```
java.lang.IllegalArgumentException: fromIndex(0) > toIndex(-1)
	at java.util.Arrays.rangeCheck(Arrays.java:113)
	at java.util.Arrays.fill(Arrays.java:2903)
	at org.chocosolver.util.objects.IntMap.clear(IntMap.java:194)
	at org.chocosolver.solver.search.strategy.selectors.variables.DomOverWDeg.getDecision(DomOverWDeg.java:120)
	at org.chocosolver.solver.search.loop.MoveBinaryDFS.extend(MoveBinaryDFS.java:64)
	at org.chocosolver.solver.search.loop.SearchLoop.launch(SearchLoop.java:221)
	at org.chocosolver.solver.Solver.solve(Solver.java:1099)
	at org.chocosolver.solver.Solver.findAllSolutions(Solver.java:966)
```
It only happens after finding the 5th solution in my specific problem. 

Patch of `IntMap.java` is pretty simple:
```
/**
 * Removes all of the mappings from this map.
 * The map will be empty after this call returns.
 */
  public void clear() {
        if (size > -1) 
        	Arrays.fill(elements, 0, size, FREE);
        size = 0;
    }
```
Somehow the IntMap `pid2arity` in `DomOverWDeg.java` is empty (`size == -1`), so that clearing it fails with the error above.

**Comment by cprudhom** [comment]
Thank you for the bug reporting and the patch.
I already encounter this bug while integrating `IntMap` and thought I fixed it. 
Even if your patch is OK, I would like to understand why `size` is below `0`.

**Comment by cprudhom** [comment]
I think I've got it: `DomOverWDeg` seems to be buggy, I'll patch it asap.

**Comment by cprudhom** [comment]
I deployed the latest develop branch on [oss.sonatype](https://oss.sonatype.org/#nexus-search;quick~choco-solver) (v3.3.3-SNAPSHOT) if you want to try the fixed version of `DomOverWDeg`.

**Comment by RobertHilbrich** [comment]
Thank you for your patch. We switched to the development branch (fixed to commit: https://github.com/chocoteam/choco3/commit/f3185f69cae516e71025749f0c8cc9b1ae94bcc8) and everything seems to work fine.

(We just had to change our implementation of the `IMonitorDownBranch` implementation a little.)
