### ISSUE TITLE
null array anti-pattern

### ISSUE THREAD

**Issue by fhermeni** [chocoteam/choco3#351]
if there is no objective, then Solver.getObjectives() returns null.
It would be more convenient to make it returns an empty array to avoid any NPE then require a special treatment in the code.

**Comment by cprudhom** [comment]
I changed the initialization to:
```java
 this.objectives = new Variable[0];
```
and the `Solver.setObjectives(Variable... objectives)` to:
```java
if(objectives == null){
    this.objectives = new Variable[0];
}else {
    this.objectives = objectives;
}
```

**Comment by fhermeni** [comment]
looks good to me
