### ISSUE TITLE
it is not possible to completely ignore events on some variables when incremental filtering on a propagator is used

### ISSUE THREAD

**Issue by gregy4** [chocoteam/choco3#352]
Hello,
  I tried to override getPropagationConditions(int) method in my propagator to optimize performance. When IntEventType.instantiation() was returned for selected variables, it worked fine. I miss a way how to ignore updates on some variables, it is not defined in IntEventType. When I tried to return 0 from the method, it ended in switch default in method IntEventScheduler.select(int) method and propagate(int,int) method of my propagator received all events.

Jan

**Comment by jgFages** [comment]
Hi Jan,

Try removing that variable from the super constructor call. Does it work?

**Comment by gregy4** [comment]
Hi Jean-Guillaume,
  it works but in the propagator I change domains of variables that I don't want to listen (changes make sense to the propagator only in combination with variables that I want to listen). I feel that it can be a problem in other parts of choco solver. Is it ok ?

**Comment by jgFages** [comment]
It is perfectly fine. You have to specify the variables you want to listen. You can then modify the variables you want. There will be no problem! For instance, this is common for some channeling constraints: one propagator reacts on A to modify B and another one does the opposite. They call each other until fixpoint...

**Comment by gregy4** [comment]
Great, maybe some update of javadoc in Propagator.getPropagationConditions for this case would be helpful for other choco users.

**Comment by cprudhom** [comment]
Hi,

I don't know which version of the javadoc you were looking at, but I re-wrote it few days ago (have a look at the develop branch if necessary).
However, I think we could deal properly with the case in which one declare VOID as a propagation condition for a variable. This means, for me, that the propagator should be aware of the variable modification. This would be a safer alternative to not declaring the variable as being part of the propagator's scope.

**Comment by gregy4** [comment]
I looked at javadoc of Propagator.getPropagationConditions() method in choco 3.3.2 released 2 weeks ago, current develop branch looks same.

If  you implement case with VOID as a propagation condition, I can easier rethink to what conditions to react compared to change in argument of super constructor. Benefit is also that everything can be in one method only. I vote for VOID :-)

**Comment by cprudhom** [comment]
I allowed declaring VOID as propagator conditions in `AbstractVariable`, updated the javadoc to specify this and add the following test (which I hope is close to what you expect):
```java
@Test(groups="1s")                                                                             
public void testGregy41(){                                                                     
    for(int i = 0 ; i < 20; i++) {                                                             
        Solver solver = new Solver("Propagation condition");                                   
        IntVar[] X = VF.enumeratedArray("X", 2, 0, 2, solver);                                 
        solver.post(new Constraint("test", new Propagator(X, PropagatorPriority.UNARY, true) { 
                                                                                               
            @Override                                                                          
            public int getPropagationConditions(int vIdx) {                                    
                if(vIdx == 0) {                                                                
                    return IntEventType.VOID.getMask();                                        
                }else{                                                                         
                    return IntEventType.ALL_EVENTS;                                            
                }                                                                              
            }                                                                                  
                                                                                               
            @Override                                                                          
            public void propagate(int evtmask) throws ContradictionException {                 
                // initial propagation                                                         
            }                                                                                  
                                                                                               
            @Override                                                                          
            public void propagate(int idxVarInProp, int mask) throws ContradictionException {  
                if(idxVarInProp == 0){                                                         
                    Assert.fail();                                                             
                }                                                                              
            }                                                                                  
                                                                                               
            @Override                                                                          
            public ESat isEntailed() {                                                         
                return ESat.TRUE;                                                              
            }                                                                                  
        }));                                                                                   
        solver.set(ISF.random(X, i));                                                          
        solver.findAllSolutions();                                                             
        Assert.assertEquals(solver.getMeasures().getSolutionCount(), 9);                       
    }                                                                                          
}                                                                                              
```

**Comment by gregy4** [comment]
Hi Charles, yes the test shows what I expected.
