### ISSUE TITLE
Restoring solution after `findOptimalSolution()`

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco3#354]
In v3.3.2, calling `findOptimalSolution(...)` did not restore the last solution found by default.
I've been suggested to add a new API, named `searchOptimalSolution(...)` which does not restore the last solution, and roll back the behavior of `findOptimalSolution(...)` to the one in v3.3.1.

I think it is a good idea or at least, a good discussion starting point.

**Comment by JLiangWaterloo** [comment]
Why not always restore the last solution?

**Comment by cprudhom** [comment]
I had the feeling that we did by default actions (ie, restoring the last solution) not easy to undo and which complicate multiple resolution process.
Morover, it was not consistent with `findSolution()` and `nextSolution()` which do not restore the last solution found (since they stop on solution, OK).

**Comment by gregy4** [comment]
I think it is a minor difference, boolean parameter to restore last solution or not would be enough - it is only post action. On the other side a lot of common sense can be needed to find out that seachOptimalSolution method exists, findOptimalSolutionRestoreLastSolution (or some other postfix alternative) is for me second choice.

In my code I iterate over solution objects directly, so restoring the last last solution is not needed for me. Both variants makes sense to me.

**Comment by cprudhom** [comment]
Your suggestion imposes to deprecate the following methods:
```java
void findOptimalSolution(ResolutionPolicy policy, IntVar objective)
void findOptimalSolution(ResolutionPolicy policy)
void findAllOptimalSolutions(ResolutionPolicy policy, IntVar objective, boolean twoSteps)
void findOptimalSolution(ResolutionPolicy policy, RealVar objective, double precision)
void findParetoFront(ResolutionPolicy policy, IntVar... objectives)
```
and add a new boolean, parameter  `restore` which forces the user to choose whether or not he wants to restore the last solution found:
```java
void findOptimalSolution(ResolutionPolicy policy, boolean restore, IntVar objective)
void findOptimalSolution(ResolutionPolicy policy, boolean restore)
void findAllOptimalSolutions(ResolutionPolicy policy, boolean restore, IntVar objective, boolean twoSteps)
void findOptimalSolution(ResolutionPolicy policy, boolean restore, RealVar objective, double precision)
void findParetoFront(ResolutionPolicy policy, boolean restore, IntVar... objectives)
```

An alternative would be to add a new setting in `Settings` to specify the expected default behavior:
```java
default boolean restoreLastSolution() {
    return false;
}
```
But, it is a less user-friendly solution.

Another one would be to always restore the last solution found, but as I said I think it is not a good idea since manually undoing it is not easy, but I can also add a new method to do that (which would certainly call `SearchLoop.reset()`).

**Comment by gregy4** [comment]
Maybe variant to restore the last solution could be default for findXXX methods, for beginners it can be easier.

**Comment by cprudhom** [comment]
After talking with @jgFages, we decided that adding new APIs with a new parameter (`restoreLastSolution`) without deprecating the other ones is the best answer to this issue.
